### ISSUE TITLE
Virtual COM port for HM-10 module?

### ISSUE THREAD

**Issue by Maxwell3e8** [that-apex/BLE_Serial#1]
This looks like what a lot of people have been looking for- creating a virtual COM port on Windows for BLE the same way as it works for regular Bluetooth. Would it work for HM-10?  Also, is it possible to post a compiled executable?

**Comment by that-apex** [comment]
Hello!

Yes, I did test this with an HM-10 module and it worked great, I can post an .exe later today when I'm home.

**Comment by that-apex** [comment]
I posted a release with an .exe.
https://github.com/that-apex/BLE_Serial/releases/tag/v0.1.1

**Comment by Maxwell3e8** [comment]
Thanks! I almost got it to work, but I think I don't know how to properly setup COM ports. When I specify some existing port, it says "Working..." but then I can't connect to that port with a terminal program. If I specify a non-existing port it says "Failed to open port"

**Comment by that-apex** [comment]
It does not create virtual ports it only connects BLE devices to existing ports.
You could use some virtual serial port application, create a port pair and connected BLE_Serial to one of the ports and your terminal application to the other one.

**Comment by Maxwell3e8** [comment]
What virtual port software you would recommend? I've tried com0com, but it didn't seem to do the right thing.

**Comment by that-apex** [comment]
This one seems to do the trick: https://freevirtualserialports.com/
The free version is enough, just click on Create Local Bridge.
It will create a port pair and it'll show it in the main menu.
![image](https://user-images.githubusercontent.com/71989950/105249002-ad337a80-5b77-11eb-98a7-a84cc8604a59.png)

Then just connect BLE_Serial to the first port, and the serial monitor to the other.

**Comment by Maxwell3e8** [comment]
Yes, got it to work! Now I am logging from a multimeter. It's an awesome program, you should blog about it somewhere!

**Comment by that-apex** [comment]
Glad I could help.

I don't really have time for blogging, it was just a hobby project that I needed for one thing. Maybe in the future I'll rewrite it to make it easier to use and I'll post it somewhere.
